### PR TITLE
Instancing practice

### PR DESCRIPTION
**Pull request by XuWenzheng**
Resend the practice, since some commits of my previous PRs were not committed by GitHub account.

### CODE REVIEW

**Comment by XuWenzheng** [comment]
@bghgary CLA issue is gone. BTW, will this be merged into master? I thought this was just a practice.

**Comment by bghgary** [comment]
> BTW, will this be merged into master?

No.

**Comment by bghgary** [comment]
Did you get a chance to figure out how to update the screenshots like @stevk mentioned in your other PR?

**Comment by XuWenzheng** [comment]
> Did you get a chance to figure out how to update the screenshots like @stevk mentioned in your other PR?

Yes, the screenshots were added in this PR. I believe the following 2 are the only screenshots for the new model, correct?
Output/Positive/Instancing/Figures/SampleImages/Instancing_13.png
Output/Positive/Instancing/Figures/Thumbnails/Instancing_13.png

**Comment by bghgary** [comment]
Ah, yes, I missed them. LGTM. Feel free to close.

**Pull request closed without merging**
