### PR TITLE
Add a new model for Instancing.

### PR DESCRIPTION
**Pull request by XuWenzheng**
This is a practice for OMG QA Offshore team, which tries to add a new model to Instancing: Two scenes using the same node. Update the readme as needed.
Please review and let us know if the code is not good enough or some files I forget to check in.

### CODE REVIEW

**Comment by stevk** [comment]
The [generated screenshot](https://github.com/KhronosGroup/glTF-Asset-Generator/blob/master/Documentation/Adding_Models.md#generate-screenshots) is missing.

Looks like I was wrong about this change requiring a change to the runtime layer.

**Comment by XuWenzheng** [comment]
@bghgary  I have signed CLA but this PR shows me it is pending check, Steven mentioned me it possible need someone on Khronos to sign off, and you may know this. One more thig, this PR is just a practice and ensure our team won't have any issue that working with you in the future,

**Comment by bghgary** [comment]
@XuWenzheng

> CLA

It looks like the commits of this PR is done with a different user than the GitHub user. This [link](https://help.github.com/en/articles/setting-your-commit-email-address) has a bit of info.

**Comment by XuWenzheng** [comment]
I forgot to set the email in git before committing the changes, so the PR wasn't made by my GitHub account.
Close the pull request, will make a new one with my GitHub account later.

**Pull request closed without merging**
